name: Sync README Sections from Multiple Repositories

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  sync-readmes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Target Repository
      uses: actions/checkout@v3

    - name: Clone Source Repositories
      run: |
        git clone https://github.com/tiktok-privacy-innovation/PETAce.git source-repo-1

    - name: Extract and Sync README Sections
      id: sync
      run: |
        declare -A TARGETS
        TARGETS=(
            ["source-repo-1/README.md ## Requirements"]="content/en/docs/petace/Getting started/_index.md" "<!-- start-section-1 -->" "<!-- end-section-1 -->"
        )

        # Function to extract the section between a given marker and the next header
        extract_section() {
            local source=$1
            local marker=$2
            awk "/^$marker/,/^## /{if(\$0 ~ /^$marker/ || \$0 ~ /^## /) next} 1" "$source"
        }
        
        # Function to replace content between markers in target file
        replace_in_file() {
            local target=$1
            local start_marker=$2
            local end_marker=$3
            local new_content=$4

            awk -v start="$start_marker" -v end="$end_marker" -v content="$new_content" '
            {print}
            $0 ~ start {print content; in_block = 1; next}
            in_block && $0 ~ end {in_block = 0; next}
            ' "$target" > tmpfile && mv tmpfile "$target"
        }

        # Sync the relevant portions to each target file
        for key in "${!TARGETS[@]}"; do
            IFS=" " read -r source marker <<< "$key"
            IFS=" " read -r target start_marker end_marker <<< "${TARGETS[$key]}"

            # Extract the section
            new_content=$(extract_section "$source" "$marker")
            
            # Replace the content in the target file between markers
            replace_in_file "$target" "$start_marker" "$end_marker" "$new_content"

            echo "Synced $marker from $source to $target between $start_marker and $end_marker"
        done

    - name: Commit Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated sync of README sections from multiple repositories"
        git push
      if: success()