name: Sync README Sections from Multiple Repositories

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-readmes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Target Repository
      uses: actions/checkout@v3

    - name: Clone Source Repositories
      run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/tiktok-privacy-innovation/PETAce.git source-repo-1

    - name: Extract and Sync README Sections
      id: sync
      run: |
        sources=(
          "source-repo-1/README.md ## Requirements"
        )
        targets=(
          "content/en/docs/petace/Getting started/_index.md"
        )
        start_markers=(
          "<!-- start-section-1 -->"
        )
        end_markers=(
          "<!-- end-section-1 -->"
        )

        extract_section() {
            local source=$1
            local marker=$2
            awk "/^$marker/,/^## /{if(\$0 ~ /^$marker/ || \$0 ~ /^## /) next} 1" "$source" | sed '$d'
        }
        
        replace_in_file() {
            local target=$1
            local start_marker=$2
            local end_marker=$3
            local new_content=$4

            awk -v start="$start_marker" -v end="$end_marker" -v content="$new_content" '
            $0 ~ start {print; in_block = 1; print content; next}
            in_block && $0 ~ end {in_block = 0; next}
            !in_block {print}
            ' "$target" > tmpfile && mv tmpfile "$target"
        }

        for i in "${!sources[@]}"; do
            source_and_marker="${sources[$i]}"
            target="${targets[$i]}"
            start_marker="${start_markers[$i]}"
            end_marker="${end_markers[$i]}"

            IFS=" ## " read -r source marker <<< "$source_and_marker"

            new_content=$(extract_section "$source" "$marker")
            
            replace_in_file "$target" "$start_marker" "$end_marker" "$new_content"

            echo "Synced $marker from $source to $target between $start_marker and $end_marker"
        done

    - name: Commit Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated sync of README sections from multiple repositories"
        git push
      if: success()